# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Thorin Butler"
description: > # this means to ignore newlines until "email:"
   No Oakenshield here

email: thorin.butler@gmail.com
#blog logo
logo: "/assets/images/magritte.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Thorin Butler'
author: 'Thorin Butler'
author_image: "/assets/images/magritte.jpg"

paginate:	5

url: "http://tsbutler.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@ThinkingBinary'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/tsbutler
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: linkedin
    url: https://linkedin.com/in/thorinbutler
    desc: Connect with me on LinkedIn      

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
